database:
  driverClass: org.h2.Driver
  user: sa
  password: sa
  url: jdbc:h2:file:./app/db
#  properties:
#    hibernate.hbm2ddl.auto: create

server:
  applicationContextPath: /app
  applicationConnectors:
    - type: http
      port: 9090
      bindHost: "localhost"
  adminContextPath: /admin
  adminConnectors:
    - type: http
      port: 9091
      bindHost: "localhost"

  gzip:
    enabled: true

logging:
  level: INFO
  loggers:
    sk.mito.jp.w: DEBUG
    org.hibernate.SQL: ALL

  appenders:
    - type: console
    - type: file
      threshold: DEBUG
      currentLogFilename: ./app/app-output.log
      archivedLogFilenamePattern: ./app/app-output-%d.log.gz
      archivedFileCount: 5
      timeZone: UTC